all: msa2.exe

msa2.exe: MSA.C TABLES.C ASSEMBLR.C MISC.C LEX.C EXPR.C MACRO.C MSA2.H LEX.H EXPR.H MACRO.H RDF.C RDF.H
	wcl MSA.C TABLES.C ASSEMBLR.C LEX.C MISC.C EXPR.C MACRO.C RDF.C -fe=msa2.exe -mc -ox -0

clean:
	del msa2.exe
	del *.obj
	del *.err
	del *.ori

install:
	copy MSA2.EXE ..\BIN\MSA2.EXE
